2024-12-09 16:13:00,452 INFO    StreamThr :174348 [internal.py:wandb_internal():85] W&B internal server running at pid: 174348, started at: 2024-12-09 16:13:00.451395
2024-12-09 16:13:00,452 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status
2024-12-09 16:13:00,453 INFO    WriterThread:174348 [datastore.py:open_for_write():87] open: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/run-n1oz89hy.wandb
2024-12-09 16:13:00,454 DEBUG   SenderThread:174348 [sender.py:send():378] send: header
2024-12-09 16:13:00,454 DEBUG   SenderThread:174348 [sender.py:send():378] send: run
2024-12-09 16:13:00,655 INFO    SenderThread:174348 [dir_watcher.py:__init__():211] watching files in: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files
2024-12-09 16:13:00,655 INFO    SenderThread:174348 [sender.py:_start_run_threads():1123] run started: n1oz89hy with start time 1733778779.489776
2024-12-09 16:13:00,663 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: check_version
2024-12-09 16:13:00,663 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: check_version
2024-12-09 16:13:00,716 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: run_start
2024-12-09 16:13:00,717 DEBUG   HandlerThread:174348 [system_info.py:__init__():26] System info init
2024-12-09 16:13:00,717 DEBUG   HandlerThread:174348 [system_info.py:__init__():41] System info init done
2024-12-09 16:13:00,717 INFO    HandlerThread:174348 [system_monitor.py:start():194] Starting system monitor
2024-12-09 16:13:00,717 INFO    SystemMonitor:174348 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-12-09 16:13:00,717 INFO    HandlerThread:174348 [system_monitor.py:probe():214] Collecting system info
2024-12-09 16:13:00,717 INFO    SystemMonitor:174348 [interfaces.py:start():188] Started cpu monitoring
2024-12-09 16:13:00,718 INFO    SystemMonitor:174348 [interfaces.py:start():188] Started disk monitoring
2024-12-09 16:13:00,718 INFO    SystemMonitor:174348 [interfaces.py:start():188] Started gpu monitoring
2024-12-09 16:13:00,718 INFO    SystemMonitor:174348 [interfaces.py:start():188] Started memory monitoring
2024-12-09 16:13:00,719 INFO    SystemMonitor:174348 [interfaces.py:start():188] Started network monitoring
2024-12-09 16:13:00,768 DEBUG   HandlerThread:174348 [system_info.py:probe():150] Probing system
2024-12-09 16:13:00,769 DEBUG   HandlerThread:174348 [system_info.py:_probe_git():135] Probing git
2024-12-09 16:13:00,788 DEBUG   HandlerThread:174348 [system_info.py:_probe_git():143] Probing git done
2024-12-09 16:13:00,788 DEBUG   HandlerThread:174348 [system_info.py:probe():198] Probing system done
2024-12-09 16:13:00,788 DEBUG   HandlerThread:174348 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-125-generic-x86_64-with-glibc2.29', 'python': '3.8.10', 'heartbeatAt': '2024-12-09T21:13:00.768929', 'startedAt': '2024-12-09T21:12:59.486190', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/cmdunham/ChemicalDataGeneration/models/ims_to_onehot_encoder.ipynb', 'codePathLocal': 'ims_to_onehot_encoder.ipynb', 'git': {'remote': 'https://github.com/CateMerfeld/ChemicalDataGeneration.git', 'commit': '0562a87200dfb164d7d7c467cf623c6218f4c3a1'}, 'email': 'catemerfeld@gmail.com', 'root': '/home/cmdunham/ChemicalDataGeneration', 'host': 'paffenroth23-1', 'username': 'cmdunham', 'executable': '/home/cmdunham/ChemicalDataGeneration/chem_data_gen/bin/python', 'cpu_count': 16, 'cpu_count_logical': 32, 'cpu_freq': {'current': 2168.7475, 'min': 1800.0, 'max': 4000.0}, 'cpu_freq_per_core': [{'current': 3478.783, 'min': 1800.0, 'max': 4000.0}, {'current': 3608.479, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 4244.328, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 4000.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 4000.0, 'min': 1800.0, 'max': 4000.0}, {'current': 4401.494, 'min': 1800.0, 'max': 4000.0}, {'current': 3632.861, 'min': 1800.0, 'max': 4000.0}, {'current': 4448.356, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 2900.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}, {'current': 1800.0, 'min': 1800.0, 'max': 4000.0}], 'disk': {'/': {'total': 438.5479202270508, 'used': 235.065185546875}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}, {'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 125.60020446777344}}
2024-12-09 16:13:00,788 INFO    HandlerThread:174348 [system_monitor.py:probe():224] Finished collecting system info
2024-12-09 16:13:00,788 INFO    HandlerThread:174348 [system_monitor.py:probe():227] Publishing system info
2024-12-09 16:13:00,789 INFO    HandlerThread:174348 [system_monitor.py:probe():229] Finished publishing system info
2024-12-09 16:13:00,789 DEBUG   SenderThread:174348 [sender.py:send():378] send: files
2024-12-09 16:13:00,790 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-metadata.json with policy now
2024-12-09 16:13:00,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: python_packages
2024-12-09 16:13:00,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:13:00,846 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: python_packages
2024-12-09 16:13:00,847 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:13:01,019 DEBUG   SenderThread:174348 [sender.py:send():378] send: telemetry
2024-12-09 16:13:01,071 INFO    wandb-upload_0:174348 [upload_job.py:push():130] Uploaded file /tmp/tmpm512a4giwandb/09vgoct0-wandb-metadata.json
2024-12-09 16:13:01,656 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/requirements.txt
2024-12-09 16:13:01,656 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:13:01,656 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-metadata.json
2024-12-09 16:13:03,656 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:13:06,020 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:08,305 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:08,306 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:08,306 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:08,307 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:08,657 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:11,308 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:15,676 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:15,676 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:15,676 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:15,677 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:15,844 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:13:15,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:13:16,659 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:17,004 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:22,005 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:23,031 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:23,032 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:23,032 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:23,033 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:23,660 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:27,034 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:30,469 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:30,470 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:30,470 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:30,471 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:30,662 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:30,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:13:30,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:13:32,961 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:33,663 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/config.yaml
2024-12-09 16:13:37,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:37,845 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:37,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:37,846 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:38,664 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:38,847 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:43,847 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:45,187 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:45,187 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:45,187 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:45,189 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:45,665 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:45,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:13:45,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:13:48,906 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:52,541 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:52,541 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:52,542 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:52,543 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:13:52,596 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:13:52,666 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:13:54,598 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:54,642 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:13:54,667 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:13:56,651 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:13:56,667 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:13:58,652 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:13:58,667 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:13:59,653 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:13:59,929 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:13:59,929 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:13:59,929 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:13:59,930 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:00,668 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:00,668 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:00,719 DEBUG   SystemMonitor:174348 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-12-09 16:14:00,720 DEBUG   SenderThread:174348 [sender.py:send():378] send: stats
2024-12-09 16:14:00,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:14:00,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:14:04,950 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:07,286 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:07,287 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:07,287 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:07,287 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:07,669 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:10,288 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:14,636 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:14,637 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:14,637 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:14,638 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:14,671 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:14,682 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:14:15,683 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:15,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:14:15,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:14:16,671 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:17,671 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:20,941 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:21,995 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:21,996 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:21,996 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:21,996 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:22,672 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:25,997 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:29,378 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:29,378 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:29,379 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:29,380 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:29,425 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:14:29,674 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:30,674 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:30,721 DEBUG   SenderThread:174348 [sender.py:send():378] send: stats
2024-12-09 16:14:30,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:14:30,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:14:31,996 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:36,729 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:36,729 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:36,730 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:36,730 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:37,676 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:37,730 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:42,731 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:44,087 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:44,088 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:44,088 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:44,089 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:44,135 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:14:44,678 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:44,678 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:45,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:14:45,846 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:14:47,927 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:51,401 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:14:51,402 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:14:51,402 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:14:51,402 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:14:51,679 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:14:53,403 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:14:53,680 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:14:58,403 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:00,721 DEBUG   SenderThread:174348 [sender.py:send():378] send: stats
2024-12-09 16:15:00,769 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:15:00,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:15:00,845 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:15:02,682 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:15:03,992 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:08,993 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:11,609 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:15:11,610 DEBUG   SenderThread:174348 [sender.py:send():378] send: files
2024-12-09 16:15:11,610 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file media/images/PCA of Predicted Chemical Embeddings_15_1544d27d5a39ad817197.png with policy now
2024-12-09 16:15:11,610 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:15:11,610 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:15:11,611 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:15:11,656 ERROR   wandb-upload_0:174348 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-12-09 16:15:11,656 ERROR   wandb-upload_0:174348 [internal_api.py:execute():345] {"errors":[{"message":"run ims_encoder_decoder/n1oz89hy not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-12-09 16:15:11,656 ERROR   Thread-121:174348 [step_upload.py:_handle_event():144] Failed to upload file: /tmp/tmpm512a4giwandb/2fapa8ne-media/images/PCA of Predicted Chemical Embeddings_15_1544d27d5a39ad817197.png
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2357, in upload_urls
    query_result = self.gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-09 16:15:11,658 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:15:11,685 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:15:11,685 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/media/images/PCA of Predicted Chemical Embeddings_15_1544d27d5a39ad817197.png
2024-12-09 16:15:11,685 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/media/images
2024-12-09 16:15:11,685 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/media
2024-12-09 16:15:11,731 ERROR   wandb-upload_0:174348 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-12-09 16:15:11,731 ERROR   wandb-upload_0:174348 [internal_api.py:execute():345] {"errors":[{"message":"run ims_encoder_decoder/n1oz89hy not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-12-09 16:15:11,731 ERROR   Thread-121:174348 [step_upload.py:_handle_event():144] Failed to upload file: /tmp/tmpm512a4giwandb/yqs305cw-media/images/PCA of Predicted Chemical Embeddings_15_1544d27d5a39ad817197.png
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2357, in upload_urls
    query_result = self.gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-09 16:15:12,684 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:15:14,820 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:15,845 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: stop_status
2024-12-09 16:15:15,846 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: stop_status
2024-12-09 16:15:19,317 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: partial_history
2024-12-09 16:15:19,318 DEBUG   SenderThread:174348 [sender.py:send():378] send: files
2024-12-09 16:15:19,318 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file media/images/PCA of Predicted Chemical Embeddings_16_c566e5c857748656a1bd.png with policy now
2024-12-09 16:15:19,318 DEBUG   SenderThread:174348 [sender.py:send():378] send: history
2024-12-09 16:15:19,318 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: summary_record
2024-12-09 16:15:19,319 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:15:19,363 ERROR   wandb-upload_0:174348 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-12-09 16:15:19,363 ERROR   wandb-upload_0:174348 [internal_api.py:execute():345] {"errors":[{"message":"run ims_encoder_decoder/n1oz89hy not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-12-09 16:15:19,363 ERROR   Thread-121:174348 [step_upload.py:_handle_event():144] Failed to upload file: /tmp/tmpm512a4giwandb/l7tmha7f-media/images/PCA of Predicted Chemical Embeddings_16_c566e5c857748656a1bd.png
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2357, in upload_urls
    query_result = self.gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-09 16:15:19,686 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:15:19,686 INFO    Thread-122:174348 [dir_watcher.py:_on_file_created():271] file/dir created: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/media/images/PCA of Predicted Chemical Embeddings_16_c566e5c857748656a1bd.png
2024-12-09 16:15:19,686 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/media/images
2024-12-09 16:15:19,730 ERROR   wandb-upload_0:174348 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-12-09 16:15:19,730 ERROR   wandb-upload_0:174348 [internal_api.py:execute():345] {"errors":[{"message":"run ims_encoder_decoder/n1oz89hy not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-12-09 16:15:19,730 ERROR   Thread-121:174348 [step_upload.py:_handle_event():144] Failed to upload file: /tmp/tmpm512a4giwandb/rp2jmuq9-media/images/PCA of Predicted Chemical Embeddings_16_c566e5c857748656a1bd.png
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2357, in upload_urls
    query_result = self.gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-12-09 16:15:19,898 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:19,968 DEBUG   SenderThread:174348 [sender.py:send():378] send: telemetry
2024-12-09 16:15:19,968 DEBUG   SenderThread:174348 [sender.py:send():378] send: exit
2024-12-09 16:15:19,968 INFO    SenderThread:174348 [sender.py:send_exit():585] handling exit code: 0
2024-12-09 16:15:19,968 INFO    SenderThread:174348 [sender.py:send_exit():587] handling runtime: 139
2024-12-09 16:15:19,968 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:15:19,969 INFO    SenderThread:174348 [sender.py:send_exit():593] send defer
2024-12-09 16:15:19,969 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:19,969 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 0
2024-12-09 16:15:19,969 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:19,969 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 0
2024-12-09 16:15:19,969 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 1
2024-12-09 16:15:19,969 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:19,969 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 1
2024-12-09 16:15:19,969 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:19,969 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 1
2024-12-09 16:15:19,969 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 2
2024-12-09 16:15:19,969 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:19,969 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 2
2024-12-09 16:15:19,969 INFO    HandlerThread:174348 [system_monitor.py:finish():203] Stopping system monitor
2024-12-09 16:15:19,969 DEBUG   SystemMonitor:174348 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-12-09 16:15:19,970 INFO    HandlerThread:174348 [interfaces.py:finish():200] Joined cpu monitor
2024-12-09 16:15:19,970 DEBUG   SystemMonitor:174348 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-12-09 16:15:19,970 INFO    HandlerThread:174348 [interfaces.py:finish():200] Joined disk monitor
2024-12-09 16:15:20,062 INFO    HandlerThread:174348 [interfaces.py:finish():200] Joined gpu monitor
2024-12-09 16:15:20,062 INFO    HandlerThread:174348 [interfaces.py:finish():200] Joined memory monitor
2024-12-09 16:15:20,062 INFO    HandlerThread:174348 [interfaces.py:finish():200] Joined network monitor
2024-12-09 16:15:20,063 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:20,063 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 2
2024-12-09 16:15:20,063 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 3
2024-12-09 16:15:20,063 DEBUG   SenderThread:174348 [sender.py:send():378] send: stats
2024-12-09 16:15:20,064 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:20,064 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 3
2024-12-09 16:15:20,064 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:20,064 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 3
2024-12-09 16:15:20,064 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 4
2024-12-09 16:15:20,064 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:20,064 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 4
2024-12-09 16:15:20,065 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:20,065 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 4
2024-12-09 16:15:20,065 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 5
2024-12-09 16:15:20,065 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:20,065 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 5
2024-12-09 16:15:20,065 DEBUG   SenderThread:174348 [sender.py:send():378] send: summary
2024-12-09 16:15:20,066 INFO    SenderThread:174348 [sender.py:_save_file():1389] saving file wandb-summary.json with policy end
2024-12-09 16:15:20,066 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:20,066 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 5
2024-12-09 16:15:20,066 INFO    SenderThread:174348 [sender.py:transition_state():613] send defer: 6
2024-12-09 16:15:20,066 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: defer
2024-12-09 16:15:20,067 INFO    HandlerThread:174348 [handler.py:handle_request_defer():184] handle defer: 6
2024-12-09 16:15:20,067 DEBUG   SenderThread:174348 [sender.py:send_request():405] send_request: defer
2024-12-09 16:15:20,067 INFO    SenderThread:174348 [sender.py:send_request_defer():609] handle sender defer: 6
2024-12-09 16:15:20,072 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: status_report
2024-12-09 16:15:20,115 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:20,115 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:15:20,687 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/wandb-summary.json
2024-12-09 16:15:20,968 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: poll_exit
2024-12-09 16:15:21,228 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:21,228 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:15:21,687 INFO    Thread-122:174348 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/files/output.log
2024-12-09 16:15:23,529 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:23,529 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:15:23,529 INFO    SenderThread:174348 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-12-09 16:15:25,969 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:27,658 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:27,658 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:15:30,970 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:31,220 ERROR   FileStreamThread:174348 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/catemerfeld/ims_encoder_decoder/n1oz89hy/file_stream
NoneType: None
2024-12-09 16:15:35,971 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:36,946 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:36,946 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:15:40,972 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:45,973 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:50,974 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:55,975 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:15:56,092 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:15:56,092 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:16:00,975 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:05,976 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:10,977 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:15,978 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:20,978 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:25,979 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:30,166 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:16:30,166 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:16:30,980 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:35,981 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:40,981 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:45,982 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:50,983 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:16:55,983 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:00,984 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:05,985 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:10,986 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:15,986 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:20,987 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:25,988 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:30,988 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:35,989 DEBUG   HandlerThread:174348 [handler.py:handle_request():158] handle_request: keepalive
2024-12-09 16:17:39,941 ERROR   SenderThread:174348 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-12-09 16:17:39,941 ERROR   SenderThread:174348 [internal_api.py:execute():345] {"errors":[{"message":"run n1oz89hy was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-09 16:17:39,984 INFO    WriterThread:174348 [datastore.py:close():296] close: /home/cmdunham/ChemicalDataGeneration/models/wandb/run-20241209_161259-n1oz89hy/run-n1oz89hy.wandb
2024-12-09 16:17:39,990 INFO    HandlerThread:174348 [handler.py:finish():882] shutting down handler
2024-12-09 16:17:40,734 ERROR   StreamThr :174348 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2188, in upsert_run
    response = self.gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 327, in _process
    self._sm.send(record)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 385, in send
    send_handler(record)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 407, in send_request
    send_handler(record)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 635, in send_request_defer
    self.debounce(final=True)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 536, in debounce
    self._maybe_update_config(always=final)
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 513, in _maybe_update_config
    self._debounce_config()
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 542, in _debounce_config
    self._api.upsert_run(
  File "/home/cmdunham/ChemicalDataGeneration/chem_data_gen/lib/python3.8/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run n1oz89hy was previously created and deleted; try a new run name (Error 409: Conflict)
